name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Cambia 'main' por el nombre de la rama que desees monitorear

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t my-docker-image:latest .
        docker tag my-docker-image:latest ${{ secrets.DOCKER_USERNAME }}/my-docker-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-docker-image:latest
      env:
        DOCKER_CLI_ACI: "1"
